About Page Mobile Responsiveness
chrisj117/CS-472-GROUP-2-PROJECT pull request #133
Opened 2023-12-02 05:08 UTC by tresimovic

**_WHAT DOES THIS PR DO?_**
 - Fixes some padding and font-size issues on the About Page so it displays nicely on mobile screens.
 - Before: (iPhone 12 Pro - 390x844 dimensions)
![Screenshot from 2023-12-01 20-54-03](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143685176/16f3c2ef-3af0-432b-958c-71acb4cd7e4d)

 - After: (iPhone 12 Pro - 390x844 dimensions)
![Screenshot from 2023-12-01 20-55-58](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143685176/fbbf3d2a-61af-4ec3-bed6-99858f64c558)

**_WHAT ISSUES ARE RELATED TO THIS PR?_**
 - https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/126

**_HOW DO I TEST OUT THIS PR?_**
 - Run the project locally
 - `cd web` then `npm run dev`
 - Go to http://localhost:5173/ in your web browser
 - Navigate to About Page and then inspect the page
 - Toggle the device toolbar and switch to iPhone 12 Pro dimensions
 - Updated About Page should appear

2023-12-02 08:56 UTC, azboss2021 approved these changes
Looks much better @tresimovic  thank you

2023-12-02 23:26 UTC, chrisj117 requested changes
In my testing, rotating the mobile screen in dark mode causes the bottom of the screen to become white as pictured:
![image](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/35480893/e085b476-7ff2-487f-a81f-e682f11b634a)
However, I found that adding `overflow-auto` to the highest level `div` fixes this issue. Otherwise, this is a big improvement on mobile, and this small bug fix should be all this PR needs.

2023-12-02 23:29 UTC, chrisj117 commented on web/src/pages/About.jsx
> +    <div className="flex flex-col items-center h-[calc(100vh-94px)] w-screen mx-auto px-4 md:max-w-screen-xl">
This line is specifically where I applied `overflow-auto` to fix the dark mode mobile bug mentioned in my review.

2023-12-03 02:43 UTC, danielogen commented
The changes look great so far...

2023-12-03 05:22 UTC, carrec-2 requested changes
Great work! Not sure if you caught some of these errors already or if you fixed them yet, but here are some issues I found. 
1. 
![home page 1](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143997122/5f201213-31fd-4ea1-8edb-464aeab949b0)
In the about page In dark mode, all the text is there but the dark mode gets cutoff on the vertical iphone 12 pro dimensions. 
2.  
![home page 2](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143997122/1a05800f-6c7e-44bf-9eeb-49ababbee6ee)
In the about page In dark mode, only the first part of text is there and the rest gets cutoff with white in the horizontal iphone 12 pro dimensions
3.  
![home page 4](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143997122/67dd7640-957a-4b5f-ba44-f8c0288f473d)
![home page 5](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143997122/8868b128-513d-4716-8cba-c37b2485fa0b)
On the home page in both light/dark mode, the  "Find your school below to leave an evaluation!" is missing in the horizontal iphone 12 pro dimensions
4.  
![home page 6](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/143997122/09f0a2da-3387-4d53-b556-42d28b98bcf5)
On the login page in dark mode, the dark mode gets cutoff in the horizontal iphone 12 pro dimensions.

2023-12-03 05:49 UTC, chrisj117 approved these changes
With the navbar changes from PR #135 , the horizontal mode's "white bar in dark mode" bug seems to have been fixed. After the merge conflicts are solved this PR should also be good to go 👍

2023-12-03 06:06 UTC, carrec-2 approved these changes

2023-12-03 20:06 UTC, tresimovic commented
I have fixed the bug related to dark mode on a rotated mobile screen, thanks for catching it.

2023-12-03 20:18 UTC, merged