Created pull request template
chrisj117/CS-472-GROUP-2-PROJECT pull request #25
Opened 2023-10-26 06:01 UTC by chrisj117

Under the docs folder, a new file called pull_request_template.md was created

2023-10-26 15:15 UTC, danielogen commented on docs/pull_request_template.md
This Looks good to me. @chrisj117, you  can me this file to `.github` directory so that it can be picked automatically whenever a new PR is raised

2023-10-26 15:16 UTC, danielogen requested changes
Looks good to me. I left one comment

2023-10-26 15:46 UTC, danielogen approved these changes

2023-10-26 17:47 UTC, danielogen commented
> Looks good to me. I left one comment

Ignore this!

2023-10-27 02:15 UTC, azboss2021 commented
Looks good chris 👍

2023-10-31 05:00 UTC, Ruaaann approved these changes
Template looks good!

2023-10-31 06:06 UTC, merged