Added corsheaders configuration to settings.py
chrisj117/CS-472-GROUP-2-PROJECT pull request #32
Opened 2023-11-01 05:40 UTC by Ruaaann

**_WHAT DOES THIS PR DO?_**

Very simple refactoring PR that adds the configuration necessary to enable the django cors-headers app in order to be used in our project. 

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- #31 

**_HOW DO I TEST OUT THIS PR?_**

  - Currently only localhost:8000 is an allowed origin.

2023-11-02 06:14 UTC, danielogen approved these changes
Hi @Ruaaann this well done!

2023-11-02 06:14 UTC, danielogen commented on api/backend/settings.py
> +CORS_ALLOWED_ORIGINS = [
This is great since our backend API is running on PORT 8000

2023-11-03 01:20 UTC, azboss2021 approved these changes
Looks good @Ruaaann This is good to avoid CORS headers when interacting with the API from frontend

2023-11-03 18:59 UTC, danielogen requested changes
Looks like we have some merge conflicts

2023-11-03 22:25 UTC, Ruaaann commented
I have addressed the merge conflicts and fixed them, this PR can be merged upon re-review!

2023-11-03 23:10 UTC, danielogen approved these changes
All conflict have been removed. Thanks @Ruaaann

2023-11-03 23:10 UTC, merged